In [2]:
import torch

In [5]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [7]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [9]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print(f'A random Tensor: {r1}')

r2 = torch.rand(2,2)
print(f'Another random Tensor: {r2}')

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print(f'Another tensor after reinitializing seeding: {r3}')

r4 = torch.rand(2,2)
print(f'Another random Tensor: {r4}')

A random Tensor: tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
Another random Tensor: tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
Another tensor after reinitializing seeding: tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
Another random Tensor: tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])


In [13]:
ones = torch.ones(2,3)
twos = torch.ones(2,3) * 2
threes = ones + twos

# Addition of same dimenion tensors is possible
print(f'{threes}')

tensor([[3., 3., 3.],
        [3., 3., 3.]])


In [16]:
r1 = torch.rand(2,3)
r2 = torch.rand(3,2)

#Not Possible
#print(r1+r2)

In [17]:
r = (torch.rand(2,2) - 0.5) * 2
print(f'A random matrix: {r}')

A random matrix: tensor([[ 0.8901, -0.5283],
        [-0.6041, -0.3345]])


In [18]:
print(f'Absolute Value: {torch.abs(r)}')

Absolute Value: tensor([[0.8901, 0.5283],
        [0.6041, 0.3345]])


In [19]:
print(f'Inverse sine of r: {torch.asin(r)}')

Inverse sine of r: tensor([[ 1.0976, -0.5566],
        [-0.6487, -0.3411]])


In [20]:
print(f'Determinant of r: {torch.det(r)}')

Determinant of r: -0.6169081330299377


In [21]:
print(f'Singular value decomposition: {torch.std(r)}')

Singular value decomposition: 0.6988239288330078


In [22]:
print(f'Average and standard deviation: {torch.std_mean(r)}')

Average and standard deviation: (tensor(0.6988), tensor(-0.1442))


In [23]:
print(f'Maximum Value: {torch.max(r)}')

Maximum Value: 0.8901034593582153
