In [2]:
import torch
import math

In [3]:
x = torch.empty(3,4)
print(x, type(x))

tensor([[-5.8838e-39,  1.1491e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]) <class 'torch.Tensor'>


In [4]:
zeroes = torch.zeros(2, 3)
ones = torch.ones(2, 3)

torch.manual_seed(123)
random = torch.rand(2,3)

print(zeroes, ones, random)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [9]:
x = torch.empty(2,2,3)
print(x)
print(x.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])


In [10]:
ex = torch.empty_like(x)
print(ex)
print(ex.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])


In [11]:
eo = torch.ones_like(x)
print(eo)
print(eo.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])


In [12]:
er = torch.rand_like(x)
print(er)
print(er.shape)

tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])
torch.Size([2, 2, 3])


In [13]:
some_floats = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_floats)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])


In [14]:
some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

tensor([ 2,  3,  5,  7, 11, 13, 17, 19])


In [15]:
more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


In [17]:
a = torch.ones(2,3, dtype=torch.float64)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [21]:
b = a.to(torch.int32)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
